coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        informational: true

ignore:
  - "src/main/java/page/poli/sdk/internal/Version.java"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true
